export const PROJECT_GET_ALL = 'PROJECT_GET_ALL';
export const PROJECT_GET = 'PROJECT_GET';
export const PROJECT_SELECT = 'PROJECT_SELECT';
export const PROJECT_CREATE = 'PROJECT_CREATE';
export const PROJECT_EDIT = 'PROJECT_EDIT';
export const PROJECT_ADD_USER = 'PROJECT_ADD_USER';
export const PROJECT_DELETE_USER = 'PROJECT_DELETE_USER';
export const PROJECT_DELETE = 'PROJECT_DELETE';
